### ISSUE TITLE
[Home inicial] Frontend - Criação de estilo master para a página

### ISSUE THREAD

**Issue by luizpbello** [TechRate-Lab/TR-Frontend#13]
Como visitante
Quando acesso a página da TechRate
Então devo encontrar uma padronização de tipos, cores e tamanhos de letra

Descrição: Criar um template master de estilos para ser utilizado na página conforme estudo de tipografias feitas anteriormente. (Obs.: Não consegui encontrar a isssue que criou as tipografias, o @Luiz mostrou na reunião mas não achei, sei que tem)

Por favor alinhem detalhes com o time de Design quanto a tamanhos, cores e formatos.

### Critérios de aceitação:
- [ ] Deve manter as cores verde conforme estudo.
- [ ] Deve utilizar até 3 nuances do verde para outros elementos e degradês.
- [ ] Deve utilizar até 5 nuances de cinza para elementos de texto.
- [ ] Deve existir somente uma nuance de cinza para elementos que sejam visíveis inativos.
- [ ] Deve existir somente uma cor de Vermelho para alerta.
- [ ] Botões devem ter margem e padding padrão.
   - [ ] Botões de call to action devem ser padrões, com fundo verde e texto branco negrito para facilitar a leitura. 
   - [ ] Botões optativos positivos devem ter o contorno fino de 1 px na cor verde e fundo branco com letras verdes.
   - [ ] Botões optativos negativos devem ter o contorno de 1 px na cor branca e fundo transparente com letras brancas.
   - [ ] Botões inativos devem ter a cor cinza de elementos inativos e texto preto.
- [ ] Criar padrões para texto parágrafo, positivo na cor preto.
- [ ] Criar padrões para texto parágrafo negativo na cor branco.
- [ ] Criar padrões de texto Headers positivo e negativo H1, H2, H3, H4.
- [ ] Criar um estilo para linha divisória horizontal de 1 px na cor cinza.
- [ ] Criar um estilo para background da homePage com fundo branco e grafismo verde.

### Exemplos gráficos

![Image](https://user-images.githubusercontent.com/50176581/241270798-b4cf3468-a1c8-49aa-944a-219341522e95.png)

![Image](https://user-images.githubusercontent.com/50176581/241270808-09943bf3-23d4-4768-b425-9d76c6f31291.png)

![Image](https://user-images.githubusercontent.com/50176581/241270816-df14f1cf-30a6-4a02-9edc-db39b76874f2.png)

![Image](https://user-images.githubusercontent.com/50176581/241270829-469761ae-b321-4012-9da7-c39745a37121.png)

![Image](https://user-images.githubusercontent.com/50176581/241270837-321cb508-b2e8-4a05-98f0-e38a93c72f6a.png)

**Comment by luizpbello** [comment]
Já coloquei criei o Theme Provider com as cores confrorme a PR #14 . Porém surgiram algumas dúvidas na tipografia @AlynneMartins.

Não está claro pra mim o tamanho pra definir as fontes aqui:


![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/04328b58-ad00-4b75-a3f6-de77f2937fa4)




Ali aparece somente o font-weight que seria a "grossura" da fonte, mas não o tamanho em pixels/rem ou outra medida. Preciso dessas especificações, do nome da fonte também.

**Comment by JohnnyKamigashima** [comment]
Em relação ao tamanho de letras, o menor tamanho será o tipo de parágrafo, ou texto normal. Ele deve ser legível a 100% de zoom do navegador. Todos os pesos H devem ser superiores ao P;

**Comment by JohnnyKamigashima** [comment]
Em relação aos botões, não creio que haja um estudo detalhado sobre eles, somente o modelo de home páge criada no figma com modelos claro e escuro. Vocês acham que seria interessante criar uma tarefa para o pessoal do Design fazer estudo sobre icones, links, imagens e botões?

**Comment by luizpbello** [comment]
Finalizado com o PR #24
