### ISSUE TITLE
[Home inicial] Frontend - Criação dos módulos dos elementos do Corpo da Home Page

### ISSUE THREAD

**Issue by luizpbello** [TechRate-Lab/TR-Frontend#19]
Como visitante
Desejo visitar a página da Techrate
Para conhecer mais sobre o projeto

Descrição: O corpo da página deverá ser autoexplicativa, com uma imagem de banner chamativo que tenha a ver com a proposta, um texto que chame atenção e leve o visitante a deixar sua experiência.

E um texto que leve o visitante a se cadastrar e conhecer o conteúdo oferecido.

Criação dos elementos do corpo da página principal conforme layout dos designers.
[FIGMA](https://www.figma.com/file/xBCUMGgXfE015N2f1w5Sfb?embed_host=share&kind=&node-id=1:2&t=92SvCj6gKOHe8XNf-1&type=design&viewer=1)

![Image](https://user-images.githubusercontent.com/50176581/241267041-24473684-6a18-43cf-8d08-da41e865a2a4.png)

Observação: Textos e imagens de fácil atualização significa que eles devem vir de uma fonte de dados externa, seja um banco de dados ou de algum arquivo de configuração, e, preferencialmente não hardcoded.

Os módulos do corpo devem ser independentes e tem que haver a possibilidade de adicionar mais módulos com mais conteúdo no futuro.

## Critérios de aceitação
- [ ] Criação do módulo de banner 
   - [ ] imagem deve ser facilmente atualizável
   - [ ] Fundo deve ser transparente para não afetar o background da página
- [ ] Todos os textos devem seguir tipografia e cor definidos no estudo
- [ ] Criação do módulo de texto de chamada principal 
   - [ ] deve ser facilmente atualizável e independente do banner 
   - [ ] deve ter até 3 tipos de pesos de texto H1, H2 e Parágrafo.
   - [ ] Título da chamada principal deve ter H1, o maior tipo de letra desta página e o texto com estilo Parágrafo.
   - [ ] H2 será utilizado eventualmente na necessidade de algum destaque menor.
   - [ ] Deverá ter um botão que leve o visitante ao formulário com o texto "Compartilhe sua experiência"

**Comment by luizpbello** [comment]
:sparkles:Adicionando as seções à página inicial:sparkles:

 :star2:Este pull request adiciona quatro seções à página inicial do projeto:

:pushpin:Todos os componentes foram desenvolvidos utilizando styled components e o tema criado em TypeScript, seguindo as melhores práticas de estilização e modularidade.

:open_file_folder:**Inicio**
:page_facing_up:Código:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/fdf5ab2a-b9c1-4f84-bfd7-318ea58310e5)

:computer:Resultado: 
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/81f873b6-ebd9-493a-9825-ff327358a534)

:open_file_folder:**Sobre**
:page_facing_up:Código:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/2a604d31-9c64-42e2-9f1e-6d763cd5ae54)

:computer:Resultado:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/95b41cbc-9f57-4569-9401-63105439f61e)

:open_file_folder:**Reputação**
:page_facing_up:Código:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/578feb2e-81ad-457a-8cfe-d18831084518)

:computer:Resultado:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/6acf94a9-45bc-44af-9d35-1158a5fdf865)

:open_file_folder:**Avaliar**
:page_facing_up:Código:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/fd06a540-9638-487d-91d9-c25f84499b14)

Resultado:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/106066785/4ef81fd1-74e2-45f2-a627-99c7f54655b1)

**Comment by JohnnyKamigashima** [comment]
OK!!

![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/1a597a95-88ce-4de1-9d6e-a7f35eafa3aa)
![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/9080b997-29f9-41e5-a877-d977275eb032)
