### ISSUE TITLE
[Home inicial] Frontend - Criação dos módulos dos elementos do Rodapé

### ISSUE THREAD

**Issue by riltonbispo** [TechRate-Lab/TR-Frontend#20]
Como visitante,
Desejo ver links e contatos no rodapé da página
Para poder contatar ou acessar rapidamente as páginas da TechRate.

Descrição: Devemos ter no rodapé elementos que identifiquem a página, contatos, termos e links úteis para mais informações.

O rodapé e seus elementos serão reaproveitados em todas as sub páginas do site. [FIGMA](https://www.figma.com/file/xBCUMGgXfE015N2f1w5Sfb?embed_host=share&kind=&node-id=1:2&t=92SvCj6gKOHe8XNf-1&type=design&viewer=1)

![Image](https://user-images.githubusercontent.com/50176581/241267146-e13304ee-320d-4c0b-b34b-de9af6493c4c.png)

## Critérios de aceitação
- [ ] Logotipo do site do mesmo tamanho que o logotipo do cabeçalho.
- [ ] Módulo de contatos
   - [ ] Deverá constar placeholder número +55 (00) 0000-0000
   - [ ] Deverá constar placeholder contato@gmail.com
- [ ] Módulo de termos legais
   - [ ] Deverá constar link "Termos de uso" com link para ""
- [ ] Módulo de redes sociais
   - [ ]  Deverá constar ícones monocromáticos Twitter, Linkedin, Facebook, Instagram com links para ""
- [ ] Módulo de Copyright
   - [ ]  com o texto centralizado "Copyright ©2023 Techrate. Todos os direitos reservados."
- [ ] Linha separadora do corpo com rodapé.
   - [ ] na cor verde
   - [ ] com espessura de 1 px

**Comment by JohnnyKamigashima** [comment]
Temos algum preview dos elementos feitos? Ja foi finalizado?

**Comment by luizpbello** [comment]
**DESCRIÇÃO DA TASK**
<hr>

Foi adicionado o componente Footer conforme o protótipo do FIGMA:

**CÓDIGO**

![image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/3f3883eb-2cd7-4b87-ac03-ebe6b59c5bb3)

<hr>

**Imagem**

![image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/9bf6b2e7-2400-411e-aaa5-2fa9192a807a)
