### ISSUE TITLE
[Home inicial] Frontend - Ajustar layout do site para versão Mobile conforme Design

### ISSUE THREAD

**Issue by luizpbello** [TechRate-Lab/TR-Frontend#38]
A página já foi feita para computadores e estudamos como ela deve aparecer em tablets. Agora, precisamos criar um novo estilo para o site ser ajustado ao tamanho mobile, especialmente no modo retrato.

Critérios de aceitação:

- [ ] O layout deve seguir as mesmas cores e tipos de letras da versão desktop.
- [ ] Os elementos não podem ter seu formato distorcido ao alterar o tamanho do dispositivo ou janela do navegador.
- [ ] Os elementos não podem ser cobertos por outros 
- [ ] Todos os elementos interagíeis devem ser acessíveis independentemente do formato do dispositivo.
- [ ] Em caso de impossibilidade de posicionar algum elemento não essencial, verificar com time de Design para removê-lo.
- [ ] Deve possuir o texto final da tarefa https://github.com/orgs/TechRate-Lab/projects/5?pane=issue&itemId=29083797
- [ ] Deve possuir texto da issue #14 aplicado como descrição do projeto no bloco principal

**Comment by luizpbello** [comment]
**DESCRIÇÃO DA TASK**
<hr>

Foi criado os breakpoints conforme o ***width*** definido no protótipo do FIGMA:
![image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/dd4f30dc-bb9a-4052-9fe9-2e4944733a38)

Depois foram feitos os ajustes para telas de tamanho de **tablet**

![image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/4d821e2c-4f51-402a-b9d2-ff6cbe36b861)

Depois preciso que o @abelardojr0 teste na tela dele, pois minha dimensão está zoada.

<hr>

Essa section não ficou de acordo com o protótipo, preciso depois rever ela:

![image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/7bf8bf95-7b4a-4319-a36f-e71d5ab204ab)

**Comment by NHDrizzt** [comment]
Teste

**Comment by NHDrizzt** [comment]
**DESCRIÇÃO DA TASK**
<hr>

Foi adicionado o layout de mobile conforme segue o design figma para os component de: Header, HeroSection, Sobre, Reputacao, Avaliar e Footer.

Para a realizao dessa task, foi necessario:
 1-  Alterar o breakpoint de desktop para 1600px.
 2-  Utilizar o conceito de Mobile First no desenvolvimento da pagina.
 3-  reestruturação do codigo existente para se adequar ao mobile.

**Comment by JohnnyKamigashima** [comment]
@NHDrizzt @luizpbello Me tag quando estiver no ar essa versão com o ajuste por favor.

**Comment by luizpbello** [comment]
@JohnnyKamigashima agora  já está lá. Eu que não tinha feito o merge ainda!

@NHDrizzt , acessei por outro PC, e deu tudo certo. Acho que foi problema no meu navegador mesmo

**Comment by rafatomaz** [comment]
@luizpbello @NHDrizzt @JohnnyKamigashima Pessoal, dei uma olhada pelo meu celular e as alterações já estão aparecendo para mim, porém em alguns casos o conteúdo ficou muito próximo da borda direita. Coloquei dois prints abaixo para evidência. O que acham? Podemos aumentar a borda?

![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/58005998/dd34cab0-1fbc-40f4-816f-cbb0e208a590)



![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/58005998/2496a5f1-0404-42d6-b4d4-3ce27dca2f24)

**Comment by JohnnyKamigashima** [comment]
@NHDrizzt, olá, existe a possibilidade de criar uma margem direita para que esses elementos não fiquem grudados no canto da tela do mobile?



![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/d5785293-6257-4f3b-8d64-6a030896b482)




![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/27cdeaac-f766-411c-8290-d337695ca7ac)

**Comment by JohnnyKamigashima** [comment]
Ajustes do layout serão tratados em outra issue, passados pelo design primeiro.
