### ISSUE TITLE
[Home inicial] Frontend - Ajustar layout do site para versão Tablet conforme Design

### ISSUE THREAD

**Issue by luizpbello** [TechRate-Lab/TR-Frontend#43]
A página já foi feita para computadores e estudamos como ela deve aparecer em tablets. Agora, precisamos criar um novo estilo para o site ser ajustado ao tamanho do tablet, especialmente no modo retrato.

Critérios de aceitação:

- [ ] O layout deve seguir as mesmas cores e tipos de letras da versão desktop.
- [ ] Os elementos não podem ter seu formato distorcido ao alterar o tamanho do dispositivo ou janela do navegador.
- [ ] Os elementos não podem ser cobertos por outros 
- [ ] Todos os elementos interagíeis devem ser acessíveis independentemente do formato do dispositivo.
- [ ] Deve possuir o texto final da tarefa https://github.com/orgs/TechRate-Lab/projects/5?pane=issue&itemId=29083797
- [ ] Deve possuir texto da issue #14 aplicado como descrição do projeto no bloco principal

**Comment by NHDrizzt** [comment]
**DESCRICAO DA TASK**

<hr>

Foi adicionado o layout de mobile conforme segue o design figma para os component de: Header, HeroSection, Sobre, Reputacao, Avaliar e Footer.

Para a realizao dessa task, foi necessario:
1- Alterar o breakpoint de desktop para 1600px.
2- Utilizar o conceito de Mobile First no desenvolvimento da pagina.
3- Reestruturação do codigo existente para se adequar ao mobile.
