### ISSUE TITLE
[Home Inicial] - Frontend - Reajustar o design Mobile

### ISSUE THREAD

**Issue by luizpbello** [TechRate-Lab/TR-Frontend#53]
Ajuste do mobile para nova identidade visual

Após criarmos uma versão mobile, alguns elementos ficaram muito grandes para a página e necessitamos reajustar para telas menores.

O layout no figma foi ajustado, fazer os ajustes após ajuste do Design.

Critérios de aceitação:

- [ ]  Ajustar o formato horizontal do mobile para 360 px
- [ ] Centralizar os componentes para que haja uma margem uniforme nos dois lados e nenhum elemento fique grudado na lateral
- [ ] Cuidar para que os elementos no cabeçalho e rodapé tenham margem e não fiquem grudados nas bordas da página
- [ ] Ajustar novo logo e cores da identidade visual

**Comment by GabiStein1** [comment]
@luizpbello vou voltar essa tarefa para "a fazer" para aguardarmos a definição de nova identidade visual e fazermos as alterações de uma vez só

**Comment by luizpbello** [comment]
Ai, seguinte @JohnnyKamigashima , @gabrielviol  e @NHDrizzt .

To batendo cabeça pra terminar essa task, preciso de ajuda

Fiz quase tudo na branch [style-mobileTake](https://github.com/TechRate-Lab/TR-Frontend/tree/style-mobileTake)

Mas não consigo deixar essa parte igual a do FIGMA:



![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/88148849/85d696d4-7033-4c9c-90ca-7ca16bcdfef2)

Se algum de vocês puder me dar um help lá, agradeço. Acredito que falte só isso.

@JohnnyKamigashima  se quiser rodar ai na sua maquina clona lá pra ver como ta ficando.

**Comment by gabrielviol** [comment]
@luizpbello 
Acabei de mandar um commit com alguns alterações, da uma olhada depois, acho que está ok agora o componente.
Depois precisamos fazer um estudo melhor sobre os breakpoints, o mobile estava com 360px, mas dando uma pesquisada rápida, muitos smartphones já ultrapassam esse tamanho.

**Comment by JohnnyKamigashima** [comment]
![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/2b833c79-39f0-436d-9a16-1014280ced01)

**Comment by JohnnyKamigashima** [comment]
Link do Design
https://user-images.githubusercontent.com/138697459/267426590-e18f538f-be4a-4295-83aa-f8e67c5f5e8f.png

**Comment by gabrielviol** [comment]
Novo PR #66  com as atualizações no mobile.
@luizpbello @JohnnyKamigashima 

Obs: Ao simular o mobile no navegador, setar a largura para no máximo 480px e pressionar F5, para que a pagina seja renderizada no tamanho mobile.

**Comment by JohnnyKamigashima** [comment]
![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/f0b094ab-d2db-4ba9-86e0-921f7daa2ed9)

Está legal, @GabiStein1 o que voce acha? Podemos cmarcar como concluido?

**Comment by GabiStein1** [comment]
movido para done
