### ISSUE TITLE
[Home Inicial] Frontend - Reajustar desktop

### ISSUE THREAD

**Issue by GabiStein1** [TechRate-Lab/TR-Frontend#57]
Ajustar desktop para nova identidade visual

A página já foi feita e nos testes alguns elementos não ficaram como desejado, em reunião foi aconselhado ajustarmos para largura de 1440 px e **centralizar** os componentes para que a página tenha os blocos centralizados.

Ajustar conforme o novo estudo ajustado pelo UX, tendo os elementos centralizados ao invés de alinhados à esquerda.

Critérios de aceitação:
- [ ] Os elementos devem estar alinhados de forma centralizada na tela, com margens iguais para os dois lados. À medida que a tela for maior, todos os elementos devem permanecer alinhados ao centro e somente o espaço vazio deverá preencher a janela.
- [ ] Ajustar cores e logo da nova identidade visual
- [ ] Fazer os ajustes finos aconselhados pelo UX.
- [ ] Aplicar novo style guide conforme novo logo

OBS: Foi pedido para o UX deixar anotado as diferenças do layout novo com o anterior para facilitar o trabalho do Front.

**Comment by gabrielviol** [comment]
Aguardando ajuste que serão entregues pelo time de UX.

**Comment by luizpbello** [comment]
@gabrielviol já tem la no figma atualização. Vai puxar essa?

**Comment by gabrielviol** [comment]
Sim, só preciso de permissão lá no figma, pra conseguir pegar a logo. @luizpbello

**Comment by gabrielviol** [comment]
PR feito com as alterações da nova identidade visual. #61 
Aguardando validação.

**Comment by luizpbello** [comment]
@JohnnyKamigashima

**Comment by JohnnyKamigashima** [comment]
![Image](https://github.com/TechRate-Lab/TR-Frontend/assets/50176581/80bab4ad-f442-40dd-9df7-fa37b4583248)
